_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
            "2":
                - 1
                - 2
                - 3
                - 55
            "3":
                - 23
                - 34
                - 35
                - 55
            "4": 3.8.16
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 64
iteration:
    value: 2
learning_rate:
    value: 0.004312293239046164
seed:
    value: 4841
